IF EXISTS (SELECT 1 FROM [{0}].sys.[database_files] AS [df] WHERE [df].[name] = 'SHRINK_DATA_TEMP') BEGIN
    ALTER DATABASE [{0}] REMOVE FILE [SHRINK_DATA_TEMP]
END

IF EXISTS (SELECT 1 FROM [{0}].sys.[filegroups] AS [f] WHERE [f].[name] = 'SHRINK_DATA_TEMP') BEGIN
    ALTER DATABASE [{0}] REMOVE FILEGROUP [SHRINK_DATA_TEMP]
END